#!/usr/bin/env bash
set -euo pipefail

# Codex NO_PROXY bypass setup (Linux)
# - Adds 3.27.43.117, 3.27.43.117:10086, localhost, and 127.0.0.1 to NO_PROXY/no_proxy.
# - Persists across reboot by updating shell profiles, and (when available) systemd user environment.d.
# - Idempotent: safe to run multiple times.

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

required=("3.27.43.117" "3.27.43.117:10086" "localhost" "127.0.0.1")

# Prefer NO_PROXY then no_proxy.
current="${NO_PROXY:-${no_proxy:-}}"
log "Current NO_PROXY/no_proxy:"
echo "  ${current}"

trim() {
  # Trim leading/trailing whitespace.
  echo "$1" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

contains() {
  local needle="$1"; shift
  local item
  for item in "$@"; do
    [[ "$item" == "$needle" ]] && return 0
  done
  return 1
}

items=()
IFS=',' read -r -a parts <<< "${current}"
for p in "${parts[@]}"; do
  p="$(trim "$p")"
  [[ -z "$p" ]] && continue
  if ! contains "$p" "${items[@]}"; then
    items+=("$p")
  fi
done

for v in "${required[@]}"; do
  if contains "$v" "${items[@]}"; then
    log "Already present: $v"
  else
    log "Adding: $v"
    items+=("$v")
  fi
done

new=""
for i in "${items[@]}"; do
  if [[ -z "$new" ]]; then
    new="$i"
  else
    new="${new},${i}"
  fi
done

log "New NO_PROXY:"
echo "  ${new}"

block_start="# >>> codex no_proxy >>>"
block_end="# <<< codex no_proxy <<<"

upsert_block() {
  local file="$1"
  local tmp

  mkdir -p "$(dirname "$file")" 2>/dev/null || true
  touch "$file"
  tmp="$(mktemp)"

  awk -v start="$block_start" -v end="$block_end" '
    BEGIN{skip=0}
    $0==start{skip=1;next}
    $0==end{skip=0;next}
    !skip{print}
  ' "$file" > "$tmp"

  cat >> "$tmp" <<EOF

$block_start
export NO_PROXY="$new"
export no_proxy="\$NO_PROXY"
$block_end
EOF

  mv "$tmp" "$file"
  log "Updated: $file"
}

# Persist for shells (common cases).
upsert_block "$HOME/.profile"
[[ -f "$HOME/.bashrc" ]] && upsert_block "$HOME/.bashrc"
[[ -f "$HOME/.zshrc" ]] && upsert_block "$HOME/.zshrc"

# Persist for GUI apps on systemd-based desktops (best-effort, user-level).
mkdir -p "$HOME/.config/environment.d" 2>/dev/null || true
conf="$HOME/.config/environment.d/99-codex-no-proxy.conf"
cat > "$conf" <<EOF
# Generated by codex no-proxy setup script.
NO_PROXY=$new
no_proxy=$new
EOF
log "Wrote: $conf"
log "Note: environment.d takes effect after re-login (or reboot) on systemd user sessions."

log "Done."
log "Recommended: open a NEW terminal to apply."
log "To apply to the CURRENT shell (choose one):"
echo "  # Option A (preferred): source your shell rc/profile file you just updated:"
echo "  #   bash: source ~/.bashrc   (or: source ~/.profile)"
echo "  #   zsh : source ~/.zshrc    (or: source ~/.profile)"
echo "  # Option B: export variables (temporary for this shell only):"
echo "  export NO_PROXY=\"$new\""
echo "  export no_proxy=\"\$NO_PROXY\""
